#       $Id: META.yml,v 1.4 2005/10/15 20:10:44 adam Exp $

name:         Log-Trivial
version:      0.02
license: gpl
version_from: lib/Log/Trivial.pm
installdirs:  site
requires:
  perl: 5.6.1
build_requires:
  Test: 0
conflicts: {}

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

provides:
  Log::Trivial:
    file: lib/Log/Trivial.pm
    version: 0.02
