---
name: Log-Trivial
version: 0.20
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for writing very simple log files
license: gpl
requires:
  perl: 5.6.1
provides:
  Log::Trivial:
    file: lib/Log/Trivial.pm
    version: 0.20
generated_by: hand
