---
abstract: 'Very simple tool for writing very simple log files'
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
build_requires: {}
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.141170'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Trivial
provides:
  Log::Trivial:
    file: lib/Log/Trivial.pm
    version: '0.40'
requires:
  perl: '5.010'
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
version: '0.40'
