--- #YAML:1.0
name: Log-Trivial
version: 0.31
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for writing very simple log files
license: gpl
distribution_type: module
requires:
  perl: 5.6.1
provides:
  Log::Trivial:
    file: lib/Log/Trivial.pm
    version: 0.31
build_requires:
  Test::More: 0
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: hand
